# =============================================================================
# Docker Compose - PokéBoutique - Override Production
# =============================================================================
# Usage: docker compose -f compose.yaml -f compose.prod.yaml up --build
# =============================================================================

services:
  # ---------------------------------------------------------------------------
  # Nginx - Reverse Proxy Production
  # Sert les fichiers statiques et proxy vers l'API
  # ---------------------------------------------------------------------------
  nginx:
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/nginx.conf:ro
      - frontend_build:/usr/share/nginx/html:ro
    depends_on:
      backend:
        condition: service_healthy
      frontend:
        condition: service_completed_successfully

  # ---------------------------------------------------------------------------
  # Frontend - Build uniquement (pas de serveur)
  # Les fichiers buildés sont copiés vers le volume partagé avec Nginx
  # ---------------------------------------------------------------------------
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: build
    volumes:
      - frontend_build:/app/dist
    healthcheck:
      disable: true
    restart: "no"
    command: ["sh", "-c", "cp -r /app/dist/* /app/dist/ 2>/dev/null || true && echo 'Build completed'"]

  # ---------------------------------------------------------------------------
  # Backend - Node.js/Express API Production
  # ---------------------------------------------------------------------------
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: production
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGO_URI=mongodb://${MONGO_USER:-admin}:${MONGO_PASSWORD:-changeme}@mongo:27017/pokemon_cards?authSource=admin
    volumes: []
    secrets:
      - mongo_password

  # ---------------------------------------------------------------------------
  # MongoDB - Base de données avec authentification
  # ---------------------------------------------------------------------------
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER:-admin}
      - MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/mongo_password
      - MONGO_INITDB_DATABASE=pokemon_cards
    secrets:
      - mongo_password

# =============================================================================
# Secrets
# =============================================================================
secrets:
  mongo_password:
    file: ./secrets/mongo_password.txt

# =============================================================================
# Volumes additionnels
# =============================================================================
volumes:
  frontend_build:
    name: pokeboutique-frontend-build
